# Generated by Django 3.2.2 on 2021-05-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Application.users')),
                ('student_name', models.CharField(max_length=256)),
                ('student_phone', models.CharField(max_length=11)),
                ('student_email', models.CharField(max_length=256)),
            ],
        ),
    ]
