# Generated by Django 3.2.2 on 2021-05-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_auto_20210521_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=256)),
                ('ms_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.message_homework')),
                ('student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.student')),
            ],
        ),
    ]
