# Generated by Django 3.2.2 on 2021-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_message_message_published_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='award_apply',
            fields=[
                ('apply_num', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=256)),
                ('award_type', models.CharField(max_length=256)),
                ('award_level', models.CharField(max_length=256)),
                ('award_order', models.CharField(max_length=256)),
                ('award_date', models.DateField()),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
                ('additional_text', models.TextField()),
            ],
        ),
    ]
