# Generated by Django 3.2.2 on 2021-05-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_alter_award_apply_award_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='award_apply',
            name='uploaded_stu',
            field=models.ForeignKey(default=2019301040030, on_delete=django.db.models.deletion.CASCADE, to='Application.student'),
            preserve_default=False,
        ),
    ]
