# Generated by Django 3.2.2 on 2021-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_award_apply_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='award_apply',
            name='checked',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
