# Generated by Django 3.2.2 on 2021-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
                ('pwd', models.CharField(max_length=256)),
                ('auth', models.CharField(max_length=256)),
            ],
        ),
    ]
