# Generated by Django 3.2.2 on 2021-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Application', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('student_num', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=256)),
                ('auth', models.CharField(max_length=256)),
            ],
        ),
    ]
