# Generated by Django 3.2.2 on 2021-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='self_description',
            field=models.TextField(null='请填写你的个人简介'),
            preserve_default='请填写你的个人简介',
        ),
    ]
