# Generated by Django 3.2.2 on 2021-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_message_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_homework',
            name='useable',
            field=models.BooleanField(auto_created=True, default=True),
            preserve_default=False,
        ),
    ]
