# Generated by Django 3.2.2 on 2021-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
