# Generated by Django 3.2.2 on 2021-05-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_other',
            fields=[
                ('useable', models.BooleanField(auto_created=True)),
                ('ms_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='message_homework',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='IMG/'),
        ),
        migrations.CreateModel(
            name='notice_other',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ms_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.message_homework')),
                ('student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.student')),
            ],
        ),
    ]
