# Generated by Django 3.2.2 on 2021-05-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_auto_20210521_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_activity',
            fields=[
                ('useable', models.BooleanField(auto_created=True)),
                ('ms_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('activity_time', models.DateTimeField()),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='message_competition',
            fields=[
                ('useable', models.BooleanField(auto_created=True)),
                ('ms_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('competition_time', models.DateTimeField()),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='message_message',
            fields=[
                ('ms_num', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('href', models.CharField(max_length=256)),
                ('send_person_student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send', to='Application.student')),
                ('target_student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='Application.student')),
            ],
        ),
        migrations.CreateModel(
            name='notice_competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ms_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.message_competition')),
                ('student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.student')),
            ],
        ),
        migrations.CreateModel(
            name='notice_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ms_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.message_message')),
                ('student_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.student')),
            ],
        ),
        migrations.DeleteModel(
            name='message_other',
        ),
        migrations.RenameModel(
            old_name='notice_other',
            new_name='notice_activity',
        ),
        migrations.AlterField(
            model_name='notice_activity',
            name='ms_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Application.message_activity'),
        ),
    ]
