# Generated by Django 3.2.2 on 2021-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_auto_20210521_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_message',
            name='useable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message_activity',
            name='useable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='message_competition',
            name='useable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='message_homework',
            name='useable',
            field=models.BooleanField(),
        ),
    ]
