# Generated by Django 3.2.2 on 2021-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_award_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award_apply',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
